version: "3.9"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    env_file:
      - ./.env # Assuming .env is in the project root
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - surrealkv://data/database.db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - app
    volumes:
      - surrealdb_data:/data # Using the named volume
    user: root

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - surrealdb
    ports:
      - $PORT:$PORT
    networks:
      - app
    command: sh -c "bun run start"

networks:
  app:
    driver: bridge

volumes:
  surrealdb_data:
    driver: local
