version: "3.9"

services:
  # surrealdb:
  #   image: surrealdb/surrealdb:latest-dev

  web:
    build:
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run server:watch
    environment:
      - NODE_ENV=development
