import React, { Fragment } from "react";

/**
 * Parses a regex string (e.g., "/pattern/flags" or "pattern") or a RegExp object,
 * and ensures the global 'g' flag is set for iterative matching.
 */
const parseRegex = (regexProp: string | RegExp): RegExp => {
  let pattern: string;
  let flags: string;

  if (regexProp instanceof RegExp) {
    pattern = regexProp.source;
    flags = regexProp.flags;
  } else {
    // string input
    const stringMatch = regexProp.match(/^\/(.+)\/([gimyus]*)$/); // Matches /pattern/flags format
    if (stringMatch) {
      pattern = stringMatch[1];
      flags = stringMatch[2];
    } else {
      // Assumes input is just the pattern string
      pattern = regexProp;
      flags = "";
    }
  }

  // Ensure 'g' flag is present for iterative matching
  if (!flags.includes("g")) {
    flags += "g";
  }

  return new RegExp(pattern, flags);
};

interface ReplaceProps {
  /** The text to perform replacements on. */
  text: string;
  /**
   * The regular expression to match.
   * Can be a RegExp object or a string.
   * If a string, it can be in the format "/pattern/flags" (e.g., "/<item>/g")
   * or just the pattern (e.g., "<item>"). The global 'g' flag is automatically added if not present.
   */
  regex: string | RegExp;
  /**
   * A function that receives a `RegExpExecArray` for each match and returns a ReactNode.
   * `matchResult[0]` is the full matched text.
   * `matchResult[1]`, `matchResult[2]`, etc., are the captured groups.
   * `matchResult.index` is the 0-based index of the match in the string.
   * `matchResult.input` is the original string.
   */
  replacer: (matchResult: RegExpExecArray) => React.ReactNode;
}

/**
 * A React component that replaces regex matches in a string with custom React content.
 */
const Replace: React.FC<ReplaceProps> = ({
  text,
  regex: regexProp,
  replacer,
}) => {
  if (!text) {
    return null;
  }

  const regex = parseRegex(regexProp);
  const parts: React.ReactNode[] = [];
  let lastIndexProcessed = 0;
  let match: RegExpExecArray | null;

  // Reset regex state if it's a stateful RegExp object passed in
  regex.lastIndex = 0;

  while ((match = regex.exec(text)) !== null) {
    // Add the text segment before the current match
    if (match.index > lastIndexProcessed) {
      parts.push(text.substring(lastIndexProcessed, match.index));
    }

    // Add the content generated by the replacer function
    parts.push(replacer(match));

    lastIndexProcessed = regex.lastIndex;

    // Guard against infinite loops for zero-width matches if the JS engine
    // doesn't automatically advance lastIndex (modern engines usually do for global regex).
    // This ensures that lastIndex is advanced for the next iteration.
    if (match[0].length === 0 && regex.lastIndex === match.index) {
      regex.lastIndex++;
    }
  }

  // Add any remaining text after the last match
  if (lastIndexProcessed < text.length) {
    parts.push(text.substring(lastIndexProcessed));
  }

  // Render the parts; React can render an array of strings and elements.
  // Using Fragment with a key for each part when mapping.
  return (
    <>
      {parts.map((part, index) => (
        <Fragment key={index}>{part}</Fragment>
      ))}
    </>
  );
};

export default Replace;
